### ISSUE TITLE
[NixIOFr] ChannelIndex and AnalogSignal mixup when loading

### ISSUE THREAD

**Issue by morales-gregorio** [NeuralEnsemble/python-neo#786] opened 2019-12-17 19:17 UTC
Dear all,

I am working with relatively big data files (>10GB) and the lazy mode for the BlackrockIO is currently my best friend. I think it is an amazing feature :)

I wanted to save the processed data as `.nix` files, but unfortunately no lazy mode is available and it becomes quite complicated to work with the big datafiles. Is there a plan to implement it? Is there already a developer/beta version of this?

I am using neo `0.8.0` and nixio `v1.5.0b4`.

All best,

Aitor

**Comment by achilleas-k** [comment] 2019-12-20 14:23
The are two NIX readers in Neo, the old IO that also supports writing (NixIO) and the new Raw-based class that only supports reading (NixIOFr).  The latter, NixIOFr, uses the raw IO API and supports lazy loading.

The following should work with your package versions.

```python
io = neo.NixIOFr("stuff.nix")
blk = io.read_block(lazy=lazy)

signalproxy = blk.segments[0].analogsignals[0]
print(signalproxy)  # AnalogSignalProxy object
signal = signalproxy.load()
print(signal)  # AnalogSignal data
```

**Comment by rgutzen** [comment] 2020-02-12 13:41
Thank you for that the info. I'm trying NixIOFr now as you suggested, but run into a ValueError `Not a location (invalid object ID)`

Here a minimal code:
```
asig = neo.AnalogSignal(np.arange(100).reshape((10,10)),
                        units='mV',
                        sampling_rate=1000*pq.Hz)
blk = neo.Block()
blk.segments.append(neo.Segment())
blk.segments[0].analogsignals.append(asig)

with neo.NixIO('temp.nix') as io:
    io.write_block(blk)

with neo.NixIOFr('temp.nix') as io:
    blk = io.read_block(lazy=True)

blk.segments[0].analogsignals[0].load()
```

neo: 0.9.0dev
nixio : v1.5.0b4

**Comment by achilleas-k** [comment] 2020-02-12 15:01
The file is closed when exiting the context manager, so there's no way to load the data from the file outside the context block.
This should work:
```python
import neo
import numpy as np
import quantities as pq


asig = neo.AnalogSignal(np.arange(100).reshape((10, 10)),
                        units='mV',
                        sampling_rate=1000*pq.Hz)
blk = neo.Block()
blk.segments.append(neo.Segment())
blk.segments[0].analogsignals.append(asig)

with neo.NixIO('temp.nix') as io:
    io.write_block(blk)

with neo.NixIOFr('temp.nix') as io:
    blk = io.read_block(lazy=True)
    blk.segments[0].analogsignals[0].load()
```

Alternatively, you can keep the `io` reference around and close it manually at the end of the script, instead of using the `with` context manager.

**Comment by rgutzen** [comment] 2020-02-25 14:42
Sorry to append another NixIOFr related issue here.
In the above example code, when adding an array annotation `channel_names` to the analogsignal, the file can no longer be read with NixIOFr (but works with the regular NixIO), irrespective of lazy loading.
```
TypeError: type object got multiple values for keyword argument 'channel_names'
```
It seems that the basefromrawio automatically constructs channel_indexes which take over the array annotations from other neo objects, and thus conflicts with the ChannelIndex keyword argument `channel_names`.

**Comment by achilleas-k** [comment] 2020-02-25 16:14
We added support for array annotations in the NIXIO rather recently (relatively speaking) and I'm not sure what we did for the raw IO for NIX.  I suspect the issue is we didn't add the support or we're somehow reading channels wrong.  I'm almost certain there's something in the way the ChannelIndexes are created in the NixIOFr that isn't 100% compatible with all situations.  I'll have to look into this.

**Comment by morales-gregorio** [comment] 2020-03-04 10:42
Hi! I have also encountered the issue with the error message:
```
TypeError: type object got multiple values for keyword argument 'channel_names'
```
Has there been any patch for this?

**Comment by achilleas-k** [comment] 2020-03-04 11:39
I can see where the issue is coming from but I'm not sure how to properly solve it and what the intended behaviour should be.

The core issue, I think, is that the RawIO doesn't really create the same object structure that was written to the file.  At least for NIX, channels are created from signals, so even if the original Neo structure that was written to a NIX file did not contain any `ChannelIndex` objects, the structure that's created when read back through the NIXRawIO does.  This has been the source of quite a bit of confusion for me and @hkchekc (who wrote the NIXRawIO) and I'm still not entirely sure that what we're doing with the NIXRawIO (and by extension the NixIOFr) is exactly what the RawIO specification dictates.

I think (though I'm pretty sure I've confirmed this a couple of times with some of the developers) that one of the issues is that the RawIO doesn't really work for any arbitrary Neo structure.  It expects a certain symmetry between the the `Segment` and `ChannelIndex` subtrees of each `Block`.  This is why a NIX file that has no `ChannelIndex` objects in it, when read through the NixIOFr, will end up with a number of `ChannelIndex`es.  This causes the issue we have here, since the array annotations from `AnalogSignal` end up in the `ChannelIndex` constructor (see linked code below: the `ChannelIndex` is created as a result of the existence of the signals and inherits their annotations, I believe) and the `channel_names` array annotation conflicts with the default `ChannelIndex` property of the same name.

https://github.com/NeuralEnsemble/python-neo/blob/a745220a14098cbb9dd79c476aab85bc84656a05/neo/io/basefromrawio.py#L150-L154

If you use a unique name for an array annotations on the signal and then load it back through NixIOFr, you'll see that the annotations from the `AnalogSignal` end up on the `ChannelIndex`.  I honestly have no idea if this is the correct behaviour or not, so please let me know if it's incorrect.  I suspect that the NIXRawIO might be mixing up channels and signals when constructing the signal channels header, so things that are meant to create an `AnalogSignal` end up on the `ChannelIndex` and vice versa.

**Comment by morales-gregorio** [comment] 2020-03-04 13:36
Hey Achilleas,

That is exactly what is happening.

In my case I have a `.nix` file that only contains `AnalogSignal`s, where I have also added some `array_annotations`. I do not have any `ChannelIndex`es and would therefore not expect to have them created by the IO.

If I use the `neo.io.NixIO`, which inherits from `BaseIO` I see that the structure I created is conserved. However, that does not provide a lazy loading mode that I need for dealing with large files.

If I use the `neo.NixIOFr`, channelindexes are created with the same annotations as the analogsignals. If those annotations are called `channel_names` the above error occurs, but if the annotations are named otherwise no error appears.

As an illustration of what I am doing with my files:
```
from neo.io.nixio import NixIO
import neo
import numpy as np
import quantities as pq

# Create a block
block = neo.Block(name='Test NixIOFr')
block.segments = [neo.Segment()]

# Enrich with analog signal data
anno_dict = {'anno1': [0, 1, 2], 'anno2': ['C', 'P', 'F']}
anasig = neo.core.AnalogSignal(np.random.rand(100, 3),
                               sampling_rate=100*pq.Hz,
                               units=pq.mV,
                               array_annotations=anno_dict)
block.segments[0].analogsignals = [anasig]

# Save the block
with NixIO('foo.nix', mode='ow') as io:
    io.write(block)

# Load
with NixIO('foo.nix') as io:
    block2 = io.read_block()
    print('NixIO children of Block: ')
    print(block2.children)

with neo.NixIOFr('foo.nix') as io:
    block3 = io.read_block()
    print('\nNixIOFr children of Block: ')
    print(block3.children)
```
```
NixIO children of Block: 
(<neo.core.segment.Segment object at 0x7ff09d301a50>,)

NixIOFr children of Block: 
(<neo.core.segment.Segment object at 0x7ff09d33b4d0>, <neo.core.channelindex.ChannelIndex object at 0x7ff09d33b6d0>)
```

And if the array annotation is `channel_names`:
```
from neo.io.nixio import NixIO
import neo
import numpy as np
import quantities as pq

# Create a block
block = neo.Block(name='Test NixIOFr')
block.segments = [neo.Segment()]

# Enrich with analog signal data
anno_dict = {'channel_names': [0, 1, 2], 'anno2': ['C', 'P', 'F']}
anasig = neo.core.AnalogSignal(np.random.rand(100, 3),
                               sampling_rate=100*pq.Hz,
                               units=pq.mV,
                               array_annotations=anno_dict)
block.segments[0].analogsignals = [anasig]

# Save the block
with NixIO('foo.nix', mode='ow') as io:
    io.write(block)

# Load
with NixIO('foo.nix') as io:
    block2 = io.read_block()
    print('NixIO children of Block: ')
    print(block2.children)

with neo.NixIOFr('foo.nix') as io:
    block3 = io.read_block()
    print('\nNixIOFr children of Block: ')
    print(block3.children)
```
```
NixIO children of Block: 
(<neo.core.segment.Segment object at 0x7f76b2b10690>,)

Traceback (most recent call last):
  File "foo_nix_test.py", line 25, in <module>
    block2 = io.read_block()
  File "/users/morales/miniconda3/envs/rs_data/lib/python3.7/site-packages/neo/io/nixio_fr.py", line 23, in read_block
    load_waveforms)
  File "/users/morales/miniconda3/envs/rs_data/lib/python3.7/site-packages/neo/io/basefromrawio.py", line 154, in read_block
    **chidx_annotations)
TypeError: type object got multiple values for keyword argument 'channel_names'
```

I would expect a behavior like the NixIO, without creating new attributes that the users did not put there themselves.

**Comment by achilleas-k** [comment] 2020-03-04 13:54
That's understandable, but I think this is not possible with the RawIO.  Unfortunately, the RawIO doesn't cover every kind of Neo structure (see linked code below for a description of what the RawIO expects).

https://github.com/NeuralEnsemble/python-neo/blob/a745220a14098cbb9dd79c476aab85bc84656a05/neo/rawio/baserawio.py#L20-L26

Based on this expectation, the `AnalogSignal` objects in the file end up defining a set of `signal_channels` in the RawIO and when this is read through the `BaseFromRaw` class, the `signal_channels` are converted to `AnalogSignal` and `ChannelIndex` objects.

It would be great if the RawIO could generalise to all kinds of Neo structures, even potentially "invalid" or infrequent ones, but I don't know if there are any plans for that.

@samuelgarcia Any thoughts on this?

**Comment by rgutzen** [comment] 2020-03-04 14:12
Couldn't at least the TypeError in the meanwhile be prevented by changing
```
 neo_channel_index = ChannelIndex(index=ind_within, 
                                  channel_names=ch_names, 
                                  channel_ids=all_channels[ind_abs]['id'], 
                                  name='Channel group {}'.format(i), 
                                  **chidx_annotations) 
```
to
```
 neo_channel_index = ChannelIndex(index=ind_within, 
                                  channel_names=ch_names, 
                                  channel_ids=all_channels[ind_abs]['id'], 
                                  name='Channel group {}'.format(i))
neo_channel_index.annotations.update(chidx_annotations) 
```
?

**Comment by samuelgarcia** [comment] 2020-03-10 13:49
Hi all,
sorry for the delay.

At rawIO level there is no annoation for ChannelIndex but annotation per "channel" for AnalogSignal, SpikeTrain , Event or Epoch.

A "channel" is across segment.

In BaseFromRaw, the class that wrapp rawio to io, theses by channel annotation were routed either to the object (AnalogSIgnal) or the container across segment (channelindex).
But it was done in a dirty and lazy way.


Maybe the wanted behavior would to have this array_annoations in both.

A main reason of this in between behavior is that ChjannelIndex should disappear in next object model.
So I did not rush to change the behavior.

The good new is : we can be change this behavior quite quickly because every thing is  in BaseFromRaw.

@rgutzen this is the good fix : could you do a PR ?

We could also make an extended change to copy this chidx_annotations to every AnalogSignal. It is redundant bu convinient.

**Comment by samuelgarcia** [comment] 2020-07-23 13:33
I think we can now close this.
A fix is already there. And ChannelIndex will be removed from basefromrawio.py soon.

**Closed by samuelgarcia** 2020-07-23 13:33 UTC
Labels: IO
