### ISSUE TITLE
Question-How are streams determined from files?

### ISSUE THREAD

**Issue by AbhiSwamiUConn** [NeuralEnsemble/python-neo#1507] opened 2024-07-11 18:44 UTC
For example, I have a plexon file that contains data grouped into 3 catagories.  The wideband, the field potential of the wideband, and the spikes from the wideband.  When reading the file and accessing a specific stream, the field potential is grouped into one stream and the wideband as well as the spikes are grouped into another stream.  How are these streams determined and is it possible to separate the wideband and spikes into separate streams so I am able to only access one or the other?  The wideband and spikes both have a sampling frequency of 40,000 hertz while the field potential has a sampling frequency of 10,000 hertz?

**Comment by zm711** [comment] 2024-07-12 11:32
plexon 1 or plexon 2? (plx for pl2 files). The docs explain the general idea [here](https://neo.readthedocs.io/en/latest/rawio.html). 

But basically if the sampling frequencies are different they have to be different streams. I'm surprised Wideband and spikes are in the same stream. Once you let me know which plexon I'll dig into more :)

**Comment by zm711** [comment] 2024-07-12 13:33
I see. yeah that might be a little bit of poor organization on our part. It seems like with the current setup you would just have to do a channel slice to get the correct channel for your purposes instead. Could you do the following and put it here.

```python
from neo.rawio import PlexonRawIO

reader = PlexonRawIO(file_name)

reader.parse_header()

print(reader)
print(reader.header)
```

Once I double check how that displays I could check to see if there is a way to split those into separate streams. I might need a test file though.

**Comment by zm711** [comment] 2024-07-12 13:37
That's why I'm having you run the print reader and print reader.header. If we aren't labeling the channels right, then it would be impossible, but often we give the channel's "names" which you could use to do the slice. Could you do the script I posted above so we can see if it is possible or whether we need to patch that right away ?

**Comment by zm711** [comment] 2024-07-12 14:11
Spikeinterface defaults to the channel_ids

so above we have ('WB01', '0',), so channel_name 'WB01' is channel_id '0' and channel_index 0. So yes for a `ChannelSliceRecording` in this case you slice from  '0' - '15' to only get the WB channels.

**Comment by zm711** [comment] 2024-07-12 14:12
It might be helpful if we make the channel_ids more meaningful in this case since we are losing WB vs spike information when going from name -> id which could cause mistakes for end users. I'll wait for some neuroconv people to weigh in, but I think if we can guarantee that the names are unique then we could use the names as the ids as well.

**Comment by h-mayorquin** [comment] 2024-07-12 14:48
Two things:
1) At spikeinterface level there is an option to change names as ids that should be used for plexon. I think this will make it easier. I will open a PR.
2) @AbhiSwamiUConn I have a question, are you referring to the channels called `SPKC` as spikes? According to a plexon engineer that contribute here recently [says](https://github.com/NeuralEnsemble/python-neo/pull/1495#issuecomment-2184274295) that is just a filtered version of the wideband . That's the reason they are the same stream, they have the same dtype, they come from the same file and they have the same sampling rate.

I think that a stream is a very unfortunate name that has already expanded to other parts of the ecosystem and has lead to a lot of confusion. The thing is that `stream` is just an implementation detail of neo. It is the part of the format data that cean be thought as a single block and put into a numpy or memmap array. That's why it is defined by having the same dtype, sampling_frequency, shape and coming from the same file. Nothing more.

The problem is that we expose this implementation detail at the user level interface by making users access the data through streams. Users then get confused thinking that stream must mean something like "a type of qualitatively different data" and in some cases it makes sense (neuropixel has a stream for ap and lf bands for example) but in some others it does not see here my own confusion in the past:

https://github.com/NeuralEnsemble/python-neo/issues/1133

I don't know if this should be made more prominent in the docs. As I mention it has lead to confusion in others parts of the ecosystem:
https://github.com/catalystneuro/roiextractors/issues/245

**Comment by h-mayorquin** [comment] 2024-07-12 15:16
Thanks for the clarification:
In spikeinterface it should be easy if we merge this PR:
https://github.com/SpikeInterface/spikeinterface/pull/3193

**Comment by zm711** [comment] 2024-07-12 16:02
Thanks for clarifying both. Sorry yeah spikes in neo are suppose to be their own thing, but if spkc if just filtered than in Neo parlance it would absolutely be in the same stream. 

I agree we should probably find a better explanation of stream for our docs!

**Comment by h-mayorquin** [comment] 2024-07-12 18:17
OK, now that https://github.com/SpikeInterface/spikeinterface/pull/3193 is merged on spikeinterface I wrote the asnwer to your question in #3196 @AbhiSwamiUConn 

I think that we can close this @zm711 or maybe you want to leave it open until we write better documentation for this? The thing is that I am not sure the stream is ever exposed on neo directly, right?

**Comment by h-mayorquin** [comment] 2024-07-12 18:19
Actually, final question @AbhiSwamiUConn. Do you happen to know what are the types of filering that is implemented for the "FP" and "SPKC" channels? It would be good for us to know more about this metadata.

**Comment by zm711** [comment] 2024-07-12 18:22
> I think that we can close this @zm711 or maybe you want to leave it open until we write better documentation for this? The thing is that I am not sure the stream is ever exposed on neo directly, right?

They are exposed. [here](https://github.com/NeuralEnsemble/python-neo/blob/8d4dc9a3dbfe1a3e0ab4602a06832b92e00511de/neo/rawio/baserawio.py#L704-L714) for example. The stream index gives us the sample rate, the gain, and the offset for the data so we can convert it and is necessary for the user functions. So I think we do need to document it. But stream itself is not exposed, just the indices of the streams. Is that your point?

**Comment by h-mayorquin** [comment] 2024-07-12 19:10
My question was not well phrased. I guess the core of my question? Do users of neo need to know about streams the same way that users of spikeinterface need to know about streams?

In spikeinterface you need to know the streams to access the data but as I am not a userr of neo I don't know how users interact with the concept of stream and if this type of confusion can arise at the neo level.

**Comment by zm711** [comment] 2024-07-12 19:30
> Do users of neo need to know about streams the same way that users of spikeinterface need to know about streams?

Yes. 

```python
reader = neo.RawIO()
reader.parse_header()
```

in this example the reader will have the memmap for all streams, but to actually pull out the data you need to specify which stream of data you want. I would actually say that spikeinterface is nicer in that it can be fed with name, whereas all the functions at the rawio level expect the stream index. So you run into the issue that if you don't know the IO it isn't clear how to get what you want 

ie how do you get digital data for intan -> you need stream_index = 3. So you basically need to look in the header to see which stream goes where. Again Intan has good names in the header, but it seems like Plexon says streams are Signal 0 and Signal 1 which aren't super helpful.

**Comment by h-mayorquin** [comment] 2024-07-12 19:56
Yes, we probably should have better signal streams in plexon but I we will need someone who actually has experimental experience with the format to venture in that direction.

**Comment by h-mayorquin** [comment] 2024-07-12 19:56
> > Actually, final question @AbhiSwamiUConn. Do you happen to know what are the types of filering that is implemented for the "FP" and "SPKC" channels? It would be good for us to know more about this metadata.
> 
> It just appears to use a combination of highpass and lowpass filtering.

Thanks, I wonder if the values of the bandpass are fixed or something that people decide at run time.

**Comment by zm711** [comment] 2024-07-17 17:49
Closing now that I have a docs issue open.

**Closed by zm711** 2024-07-17 17:49 UTC
