### ISSUE TITLE
NeuralynxIO  Failed to Read Data

### ISSUE THREAD

**Issue by marcoistasy** [NeuralEnsemble/python-neo#787] opened 2020-01-18 23:37 UTC
Hi all! I'm running the latest version of Neo and am using this code to create NeuralynxIO and read the directory of interest:

```
# import requisite dependencies

%matplotlib inline

import neo
import numpy as np
import matplotlib.pyplot as plt
from neo.io import NeuralynxIO

# read file

reader = NeuralynxIO(dirname='/home/user/Desktop/data')
```
In the data directory, there is a single `.ncs` file. However, when I run the code, this is the bug that I recieve `TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'`, with the full traceback being

```
TypeError                                 Traceback (most recent call last)
<ipython-input-17-c76154c9cc99> in <module>
----> 1 reader = NeuralynxIO(dirname='/home/user/Desktop/data')

~/anaconda3/envs/noise_reduction/lib/python3.7/site-packages/neo/io/neuralynxio.py in __init__(self, dirname, use_cache, cache_path)
     34         NeuralynxRawIO.__init__(self, dirname=dirname,
     35                                 use_cache=use_cache, cache_path=cache_path)
---> 36         BaseFromRaw.__init__(self, dirname)

~/anaconda3/envs/noise_reduction/lib/python3.7/site-packages/neo/io/basefromrawio.py in __init__(self, *args, **kargs)
     79     def __init__(self, *args, **kargs):
     80         BaseIO.__init__(self, *args, **kargs)
---> 81         self.parse_header()
     82 
     83     def read_block(self, block_index=0, lazy=False, signal_group_mode=None,

~/anaconda3/envs/noise_reduction/lib/python3.7/site-packages/neo/rawio/baserawio.py in parse_header(self)
    149 
    150         """
--> 151         self._parse_header()
    152         self._group_signal_channel_characteristics()
    153 

~/anaconda3/envs/noise_reduction/lib/python3.7/site-packages/neo/rawio/neuralynxrawio.py in _parse_header(self)
    223             # case  NO ncs but HAVE nev or nse
    224             self._timestamp_limits = [(ts0, ts1)]
--> 225             self._seg_t_starts = [ts0 / 1e6]
    226             self._seg_t_stops = [ts1 / 1e6]
    227             self.global_t_start = ts0 / 1e6

TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

I am wondering what the problem is and how to solve it? I understand what a `TypeError` is, however, am not entirely sure how it applies and how to fix it.

Thank you

**Comment by JuliaSprenger** [comment] 2020-01-19 11:13
Hi @marcoistasy!
Thanks for reporting the issue. I can't reconstruct the error you are getting based on other ncs files. Somehow it seems that the time limit extraction does not work properly for your file and such that the io assumes there is no ncs file at some point. Would it be possible for you to send this file to me so I can dig deeper into this issue? Also, does this occur with all your ncs files or is this a particular case?

**Comment by marcoistasy** [comment] 2020-01-19 14:43
Thanks so much for your quick response! This seems to occur with all my `.ncs` files. Here is an example [file](https://drive.google.com/file/d/1btC5O5E34i3BzzEVqX4kmAXc-0OIMQ7m/view?usp=sharing) that I am using and running into the same issue with. Please let me know what you find 😄

**Comment by JuliaSprenger** [comment] 2020-01-20 11:11
Hi @marcoistasy! Thanks for the file. I had a look and have good and bad news:

- the initial issue can be solved easily, as the error you are describing is caused by the file extension being '.Ncs' instead of '.ncs'.
- loading the file does still not work as this is an ancient file (3.x Cheetah version) in comparison to what the IO was implemented for (>5.x Cheetah version). I tried to extend the capability of the IO to also support the old format. However, the number of samples in the recording seem to be not consistent with the sampling rate used. I tried to find a format specification for the 3.x files, but this is not part of the public format descriptions provided by Neuralynx. Do you happen to have such a specification file coming with your data? Otherwise I will try to get some feedback from Neuralynx, but this might take a while.

For reference: The current version including the first changes to read 3.x files is here: https://github.com/INM-6/python-neo/tree/fix/787

**Comment by marcoistasy** [comment] 2020-01-20 14:52
Wow thanks so much! So this is actually a sample file from UCLA, and a tutorial that I was going through that had a script to be able to open and read them is [here](https://towardsdatascience.com/using-signal-processing-to-extract-neural-events-in-python-964437dc7c0) - perhaps this might help in some way? If you read the file through the script in the tutorial, particularly the part below, the file opens up no problem.

```
# Define data path
data_file = './UCLA_data/CSC4.Ncs'

# Header has 16 kilobytes length
header_size   = 16 * 1024  

# Open file
fid = open(data_file, 'rb')

# Skip header by shifting position by header size
fid.seek(header_size)

# Read data according to Neuralynx information
data_format = np.dtype([('TimeStamp', np.uint64),
                        ('ChannelNumber', np.uint32),
                        ('SampleFreq', np.uint32),
                        ('NumValidSamples', np.uint32),
                        ('Samples', np.int16, 512)])

raw = np.fromfile(fid, dtype=data_format)

# Close file
fid.close()

# Get sampling frequency
sf = raw['SampleFreq'][0]

# Create data vector
data = raw['Samples'].ravel()

# Determine duration of recording in seconds
dur_sec = data.shape[0]/sf

# Create time vector
time = np.linspace(0, dur_sec,data.shape[0])

# Plot first second of data
fig, ax = plt.subplots(figsize=(15, 5))
ax.plot(time[0:sf], data[0:sf])
ax.set_title('Broadband; Sampling Frequency: {}Hz'.format(sf), fontsize=23)
ax.set_xlim(0, time[sf])
ax.set_xlabel('time [s]', fontsize=20)
ax.set_ylabel('amplitude [uV]', fontsize=20)
plt.show()
```

Additionally, how were you able to ascertain that the Neuralynx file was 3.x? I would like to be able to do that for my files as well.

**Comment by samuelgarcia** [comment] 2020-01-20 16:12
@marcoistasy : be aware that with this script, you are not able to detect packet loss (gap).

The neo version try to do more that read the buffer (channel names, gain, units, gape detection) and theses actions are very sensible to version unfortunatly.

**Comment by marcoistasy** [comment] 2020-01-20 17:21
> @marcoistasy : be aware that with this script, you are not able to detect packet loss (gap).
> 
> The neo version try to do more that read the buffer (channel names, gain, units, gape detection) and theses actions are very sensible to version unfortunatly.

Thanks for the heads up! Yes I really want to use `neo` for my analysis - do you think you'll have a version that supports `Cheetah 3.X`?

**Comment by marcoistasy** [comment] 2020-01-20 17:31
> The revision number is in the file header, which you are skipping to read here. You can read it using python, e.g. via
> 
> ```python
> with open(dirname + '/CSC4.ncs', 'r') as f:
>     print(f.read(8*1024))
> ```
> 
> which should print something like:
> 
> ```python
> ######## Neuralynx Data File Header
> ## File Name: D:\Cheetah_Data\2003-2-26_13-9-56\CSC4.Ncs 
> ## Time Opened: (m/d/y): 2/26/2003  At Time: 13:9:58.250 
> -CheetahRev 3.0.6 
> -NLX_Base_Class_Name	CSC4 
> -NLX_Base_Class_Type	CscAcqEnt 
> -RecordSize  1044 
> 	-ADChannel	3	
> 	-ADGain		2	
> 	-AmpGain	5000	
> 	-AmpLowCut	1	
> 	-AmpHiCut	9000	
> 	-SubSamplingInterleave	1
> 	-SamplingFrequency	32051
> 	-ADBitVolts	0.000000488520
> 	-ADMaxValue	2047
> ```

Also, when I am running this I recieve this error: `utf-8 can't decode byte 0xb5 in position 900: invalid start byte`. I am wondering why this is being caused?

**Comment by JuliaSprenger** [comment] 2020-01-21 09:00
Hm, I would expect this error when you try to read into the actual data part of the file. But as long as you read only the first bytes this should work. Have you tried to reduce the number of bytes read?

**Comment by JuliaSprenger** [comment] 2020-01-21 15:10
Already with the simple reader provided in the UCLA tutorial you can see that there's something strange going on in the file. The individual data packets are coming with start times `raw['TimeStamp']`. If you now compare this to the number of samples combined with the sampling rate you see that a data packet seems to be longer (contain more samples) than the difference between the start time permits. Have a look here:

```python
import numpy as np

# Define data path
data_file = dirname + '/CSC4.ncs'

# Header has 16 kilobytes length
header_size = 16 * 1024

# Open file
fid = open(data_file, 'rb')

# Skip header by shifting position by header size
fid.seek(header_size)

# Read data according to Neuralynx information
data_format = np.dtype([('TimeStamp', np.uint64),
                        ('ChannelNumber', np.uint32),
                        ('SampleFreq', np.uint32),
                        ('NumValidSamples', np.uint32),
                        ('Samples', np.int16, 512)])

raw = np.fromfile(fid, dtype=data_format)

# Close file
fid.close()

# Get sampling frequency
sf = raw['SampleFreq'][0] # in hertz

packet_timestamps = raw['TimeStamp']  # in microseconds

# time difference between individual data packets
packet_time_difference = np.unique(np.diff(packet_timestamps)) # in microseconds

packet_duration = np.unique(raw['NumValidSamples']) / sf * 1e6

print('Time difference between packet beginnings [ms]:', packet_time_difference)
print('Duration of a packet [ms]:', packet_duration)
```
resulting in 
```
Time difference between packet beginnings [ms]: [15872]
Duration of a packet [ms]: [15974.54057596]
```

This is not consistent. I guess either one of the units of the saved number has changed from version 3.x to 5.x or the sampling rate stored in the header is incorrect and should rather be 32825 Hz instead of 32051 Hz as stated in the header.

**Comment by marcoistasy** [comment] 2020-01-22 11:22
> Already with the simple reader provided in the UCLA tutorial you can see that there's something strange going on in the file. The individual data packets are coming with start times `raw['TimeStamp']`. If you now compare this to the number of samples combined with the sampling rate you see that a data packet seems to be longer (contain more samples) than the difference between the start time permits. Have a look here:
> 
> ```python
> import numpy as np
> 
> # Define data path
> data_file = dirname + '/CSC4.ncs'
> 
> # Header has 16 kilobytes length
> header_size = 16 * 1024
> 
> # Open file
> fid = open(data_file, 'rb')
> 
> # Skip header by shifting position by header size
> fid.seek(header_size)
> 
> # Read data according to Neuralynx information
> data_format = np.dtype([('TimeStamp', np.uint64),
>                         ('ChannelNumber', np.uint32),
>                         ('SampleFreq', np.uint32),
>                         ('NumValidSamples', np.uint32),
>                         ('Samples', np.int16, 512)])
> 
> raw = np.fromfile(fid, dtype=data_format)
> 
> # Close file
> fid.close()
> 
> # Get sampling frequency
> sf = raw['SampleFreq'][0] # in hertz
> 
> packet_timestamps = raw['TimeStamp']  # in microseconds
> 
> # time difference between individual data packets
> packet_time_difference = np.unique(np.diff(packet_timestamps)) # in microseconds
> 
> packet_duration = np.unique(raw['NumValidSamples']) / sf * 1e6
> 
> print('Time difference between packet beginnings [ms]:', packet_time_difference)
> print('Duration of a packet [ms]:', packet_duration)
> ```
> 
> resulting in
> 
> ```
> Time difference between packet beginnings [ms]: [15872]
> Duration of a packet [ms]: [15974.54057596]
> ```
> 
> This is not consistent. I guess either one of the units of the saved number has changed from version 3.x to 5.x or the sampling rate stored in the header is incorrect and should rather be 32825 Hz instead of 32051 Hz as stated in the header.

Hi! Just figured out what the problem was with my actual file (not the test one): we don't use Cheetah but Pegasus. Do you have any plans for supporting Pegasus?

**Comment by JuliaSprenger** [comment] 2020-01-22 12:02
The IO is tested with Pegasus, too. However, this is only a single spiking data (nev) file. I would be happy to extend this also to ncs if you can provide a corresponding test file, i.e. a small file that can be added to our [public repository of test files](https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/neuralynx/Pegasus_v2.1.1).

**Comment by marcoistasy** [comment] 2020-01-22 14:25
> The IO is tested with Pegasus, too. However, this is only a single spiking data (nev) file. I would be happy to extend this also to ncs if you can provide a corresponding test file, i.e. a small file that can be added to our [public repository of test files](https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/neuralynx/Pegasus_v2.1.1).

Of course! I'll provide that right away. The file will be in Pegasus `3.X`, however - will this be a problem?

**Comment by JuliaSprenger** [comment] 2020-01-27 09:23
> > The IO is tested with Pegasus, too. However, this is only a single spiking data (nev) file. I would be happy to extend this also to ncs if you can provide a corresponding test file, i.e. a small file that can be added to our [public repository of test files](https://gin.g-node.org/NeuralEnsemble/ephy_testing_data/src/master/neuralynx/Pegasus_v2.1.1).
> 
> Of course! I'll provide that right away. The file will be in Pegasus `3.X`, however - will this be a problem?

No, this is not a problem. If the IO is not correctly loading the file we will extend it to also cover Pegasus 3.x files.

**Comment by JuliaSprenger** [comment] 2020-07-12 15:17
Hi again @marcoistasy.
Did you find a suitable file to be added to the set of test files?

**Comment by apdavison** [comment] 2020-09-07 09:49
Hi @marcoistasy - please could you send us a test file, as discussed above? Then we can dig into it further.

**Comment by JuliaSprenger** [comment] 2020-10-28 10:53
Hi @marcoistasy! I am closing the issue for now. If you still want to provide a test file, feel free to leave another comment.

**Closed by JuliaSprenger** 2020-10-28 10:53 UTC
Labels: needs-input
