### ISSUE TITLE
PlexonIO read error

### ISSUE THREAD

**Issue by madeleinea** [NeuralEnsemble/python-neo#347] opened 2017-06-21 19:55 UTC
I'm having trouble with some really simple code--I am trying to read from a .plx file and I keep getting the following error: 
TypeError: 'numpy.float64' object cannot be interpreted as an integer

I have numpy and neo installed and imported into this program--does anyone have any idea what the problem could be? I've included my code below.

from neo import io
import numpy as np

PLXfile = 'MWA03FR01111215.plx'

reader = io.PlexonIO(filename=PLXfile)
seg = reader.read_segment(cascade=True, lazy=False)

Thanks!!!

**Comment by samuelgarcia** [comment] 2017-06-22 10:40
Could you send the file please( with a file transfer service ) ?
I will try to have look.

**Comment by tlmassey** [comment] 2017-07-23 02:50
First off, @samuelgarcia, thank you for writing PlexonIO and contributing to Neo!  This is immensely helpful.

Not sure if there has been any update to the original question @madeleinea posted, but here was my experience and solution.

> Traceback (most recent call last):
>   File "neo_test2.py", line 5, in <module>
>     seg = r.read_segment()
>   File "/Users/tlmassey/Library/Python/2.7/lib/python/site-packages/neo/io/plexonio.py", line 190, in read_segment
>     sigarrays[chan] = np.zeros(nb_samples[chan])
> TypeError: 'numpy.float64' object cannot be interpreted as an index

PlexonIO line 190:
sigarrays[chan] = np.zeros(nb_samples[chan])

nb_samples[chan] returns 600806.0
type(nb_samples[chan]) returns <type 'numpy.float64'>

So the issue is that nb_samples is composed of floats rather than ints.
np.zeros expects an int as an argument.

Since nb_samples is initialized on line 141 as...
nb_samples = np.zeros(len(slowChannelHeaders))
... and the default data type of np.zeros is a float64 ...
(https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html)
... nb_samples[chan] is also going to be of type float64.

I think we also need to keep an eye on n2 (line 165) since it's added to nb_samples[chan] (line 181), but thankfully it's already an int.

**So long story short, we need to initialize nb_samples (and sample_positions on the following line, for the same reason) as type np.int:

nb_samples = np.zeros(len(slowChannelHeaders), dtype=np.int)
sample_positions = np.zeros(len(slowChannelHeaders), dtype=np.int)**

Separate error, but I'll throw it in here as long as we're talking about PlexonIO, I had to make a change to class HeaderReader().  The lines...
ival = ival.replace(str.encode('\x03'), str.encode(''))
ival = ival.replace(str.encode('\x00'), str.encode(''))
... should read ...
ival = ival.replace('\x03', '')
ival = ival.replace('\x00', '')
... since the values are already encoded as UTF-8 bytes.

With those minor changes, I was able to finish running the sample file without errors.

For reference, I'm running Python2.7 with the latest numpy, quantities, neo, etc.  I just set it all up this afternoon.  The file I ran my tests on is the example file from https://portal.g-node.org/neo/plexon/File_plexon_3.plx.

**Comment by samuelgarcia** [comment] 2017-09-26 14:38
CLosed by #385.

**Closed by samuelgarcia** 2017-09-26 14:38 UTC
Labels: bug, IO

**Comment by FMendezSlc** [comment] 2017-10-25 16:42
Hello and thank you for all your work.
I'm having this very same issue reading plexon files.
Python 3, neo 0.5.1, latest numpy, scipy, quantities.
Does the bug remains in the master branch?

**Comment by samuelgarcia** [comment] 2017-10-25 18:26
The actual release is neo 0.5.2. this fix some problem on plexonio.
Could you test it ?

In the master branch, this pelxon is a complete rewrite with plexonrawio.
Maybe, this also solve your problem.

**Comment by FMendezSlc** [comment] 2017-10-25 18:55
I'm testing neo 0.5.2 now. Thus far, using neo.io.PlexonIO(), it doesn't
show the error, but haven't been able to actually read the file though.
Could read like cascade=False, but everything is empty.
cascade=True mode keeps forever running until crash.

**Comment by FMendezSlc** [comment] 2017-10-25 21:33
plx_file ='./CA3_290917b_merged_filtered-02.plx'

plx_reader = neo.io.PlexonIO(filename=plx_file)
seg = plx_reader.read_segment(lazy=False, cascade=True)

---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-23-f0ae8df42112> in <module>()
----> 1 seg = plx_reader.read_segment(lazy=False, cascade=True)

~/anaconda/envs/py3/lib/python3.5/site-packages/neo/io/plexonio.py in
read_segment(self, lazy, cascade, load_spike_waveform)
    327                             .5 * 2. **
(global_header['BitsPerSpikeSample'])
*
    328                             dspChannelHeaders[chan]['Gain'] *
--> 329                             global_header['SpikePreAmpGain'])
    330                     waveforms = swfarrays[chan, unit] * gain * pq.mV
    331                 else:

ZeroDivisionError: float division by zero

Here, an example of the new error in PlexonIO neo 0.5.2
Meanwhile, do you know if there's a working io to read plexon files? I mean
I could save to .nex

2017-10-25 13:55 GMT-05:00 Felipe Mendez <fmendezslc@gmail.com>:

> I'm testing neo 0.5.2 now. Thus far, using neo.io.PlexonIO(), it doesn't
> show the error, but haven't been able to actually read the file though.
> Could read like cascade=False, but everything is empty.
> cascade=True mode keeps forever running until crash.
>

**Comment by samuelgarcia** [comment] 2017-10-26 07:17
I will have look.
Could you send me the file ?
Where does this file come from ? Is it directly from plexon acquisition system or is it exported by another program ?

**Comment by FMendezSlc** [comment] 2017-10-26 15:12
I'm not sure I'm allowed to share the data, since it's actual experimental
data from our lab.
I made the spike sorting of a recording made in multichannel systems MEA
environment in plexon offline sorter v.3.

Plexon offline sorter allows exporting to .plx, .nex, as well as .mat and
spreadsheet like exports in plain text or Excel files.

Tried the aforementioned .plx neo.io, then exported in .nex and couldn't
read them with neo.NeuroExplorerIO either.

By the way, neuroexplorer people offers a python script to read their files
in python, but it didn't work.

Ended up exporting in plain text and now working on rebuilding spiketrains
from there.

.plx and .nex files do work just fine in plexon offline sorter and
neuroexplorer , so you can be sure they are not corrupted or something like
that.

I really like neo/elephant project , so I would like to be able to work
with them.

Thanks anyway

**Comment by samuelgarcia** [comment] 2017-10-26 15:23
If you send a small anymomed file only to me, you can trust that I won't release this file as public nor to share this file with anybody. It is only for debbging purpose.

You can also send me a file when the material is pluged to nothing and only  recording noise as soon as the file also would trig the same bug. This is the only way I see to debug this.

If I anderstand correctly the same file made trig also a bug when exported with NeuroExplorerIO. If so, I would be also happy to have thies file.

Did you try the actual master with:
```
pip install https://github.com/NeuralEnemble/python-neo/archive/master.zip
```
