### ISSUE TITLE
KeyError when using NixIO.write_block() a file that was written by NixIO itself

### ISSUE THREAD

**Issue by grg2rsr** [NeuralEnsemble/python-neo#535] opened 2018-05-16 10:20 UTC
I am trying to read a file written by NixIO and then write it again as such

```python
import neo
from neo import NixIO

Reader = NixIO(filename='161202_A_a_pob_dil3.blk')
Blk = Reader.read_block()

Writer = NixIO(filename='testout')
Writer.write_block(Blk)
Writer.close()
```
The file '161202_A_a_pob_dil3.blk' was written by NixIO.
This causes:

```shell
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-4-9e49c9bcdfd2> in <module>()
      6 
      7 Writer = NixIO(filename='testout')
----> 8 Writer.write_block(Blk)
      9 Writer.close()

~/Dropbox/python/SeqPeelSort/src/lib/neo/neo/io/nixio.py in write_block(self, block)
    541             self._write_channelindex(chx, nixblock)
    542 
--> 543         self._create_source_links(block, nixblock)
    544 
    545     def _write_channelindex(self, chx, nixblock):

~/Dropbox/python/SeqPeelSort/src/lib/neo/neo/io/nixio.py in _create_source_links(self, neoblock, nixblock)
   1024             chxsource = nixblock.sources[chx.annotations["nix_name"]]
   1025             for name in signames:
-> 1026                 for da in self._signal_map[name]:
   1027                     da.sources.append(chxsource)
   1028 

KeyError: 'neo.analogsignal.cf7c85e319424dbbb7d2ac3d782354b5'
```
by the way, are issues generated here the preferred way to ask these things or are they better asked in the mailing list? I am not sure if this is an actual issue with the software or a user problem ... 
thanks

**Comment by grg2rsr** [comment] 2018-05-16 10:26
This does not happen on purely artificial data
```python
import neo
from neo import NixIO
import quantities as pq
import scipy as sp

Blk = neo.core.Block()
Seg = neo.core.Segment()
Asig = neo.core.AnalogSignal(sp.randn(100)*pq.V,sampling_rate=100*pq.Hz)
Seg.analogsignals.append(Asig)
Blk.segments.append(Seg)

Writer = NixIO(filename='first_write.blk')
Writer.write_block(Blk)
Writer.close()

Reader = NixIO(filename='first_write.blk')
Blk = Reader.read_block()

Writer = NixIO(filename='second_write.blk')
Writer.write_block(Blk)
Writer.close()
```
this works fine. I guess the question becomes "What can mess up the key structure in Nix and how to avoid it?"

**Comment by achilleas-k** [comment] 2018-05-16 11:39
Hello.

I'm having some trouble reproducing this issue. I'm certain it's related to the way AnalogSignal objects are referenced by a ChannelIndex. The way the NixIO handles this is by keeping track of all the AnalogSignals as they are written. It keeps a mapping of AnalogSignal → DataArray in `_signal_map`, where DataArray is the corresponding object in NIX, and then uses this map to create the secondary references.

I'm not surprised the second example works, since there's no ChannelIndex with AnalogSignals there.

I'd be interested to see the original file from the first example, or get a description of what objects it contains and how they're linked, because the error occurs in the function that's mapping the ChannelIndex → AnalogSignal references in the NIX file.

------

> by the way, are issues generated here the preferred way to ask these things or are they better asked in the mailing list?

I don't know if Samuel Garcia and Andrew Davison feel differently, but I think this is the right place for these issues.

**Comment by achilleas-k** [comment] 2018-05-16 11:51
I think I've found the issue. In the original file, is there an AnalogSignal that's only attached to a ChannelIndex (and not a Segment)?

This was a bit tricky to support in NIX but I thought I had covered it. It seems the way I check for this case isn't that smart and misses the special case only on the second write.

Here's a sample script that should reproduce your exact issue:
```python
import neo
from neo import NixIO
import numpy as np
import quantities as pq

blk = neo.Block()
seg = neo.Segment()
blk.segments.append(seg)

asig = neo.AnalogSignal(np.array([0])*pq.V, sampling_rate=100*pq.Hz)

chx = neo.ChannelIndex(index=[1])
blk.channel_indexes.append(chx)
chx.analogsignals.append(asig)

with NixIO(filename="first_write.nix", mode="ow") as writer:
    writer.write_block(blk)


with NixIO(filename="first_write.nix") as reader:
    blk = reader.read_block()

with NixIO(filename="second_write.nix", mode="ow") as writer:
    writer.write_block(blk)
```

If `asig` is appended to `seg`, the error goes away, but I understand that might not be desirable. This is a bug and I think the solution is straightforward.

**Comment by grg2rsr** [comment] 2018-05-16 11:57
Wow, fast answer, I was in the process of typing mine ... your code does reproduce the error here as well. However, in my code, the `asig` is appended to the segment.

This is the full code, where I first read the `.smr` file, slice it, dump the sliced to disk using the NixIO, and then the rest as above 
```python
import sys, os
import neo
from neo import Spike2IO
from neo import NixIO
import quantities as pq

fname = '161202_A_a_pob_dil3.smr'

Reader = Spike2IO(filename=fname)
Blk = Reader.read_block()

AnalogSignal = Blk.segments[0].analogsignals[0]
AnalogSignal = AnalogSignal.rescale('uV')

# Slice segments into trials
Segments = []
t_cut = [-4, 4]*pq.s
for t in Blk.segments[0].events[0].times:
    segment = neo.core.Segment()
    Asig = AnalogSignal.time_slice(*(t+t_cut))
    # annotate
    Asig.annotate(kind='original')
    # append to Segment
    segment.analogsignals.append(Asig)
    Segments.append(segment)

# put back to Block
Blk.segments = Segments

# write to Nix
Writer = NixIO(filename='first_write.blk')
Writer.write_block(Blk)
Writer.close()

Reader = NixIO(filename='first_write.blk')
Blk = Reader.read_block()

Writer = NixIO(filename='second_write.blk')
Writer.write_block(Blk)
Writer.close()
``` 
You can find the example file [Here](https://depot.uni-konstanz.de/cgi-bin/exchange.pl?g=3a5bgwnqsq)

**Comment by achilleas-k** [comment] 2018-05-16 12:37
Ah! I see the issue. Your new analog signals are appended to the Segment, but the old one (the one that gets sliced) is removed from the segment. When the segments on the block get replaced (`Blk.segments = Segments`), the original AnalogSignal is still part of the Neo structure, but is only accessible through the ChannelIndex (`Blk.channel_indexes[0].analogsignals`), which is the issue that my code in the previous reply reproduces.

I'm going to fix the issue in the NixIO, but if you want to work around it now there's a few things you can do, depending on what you want the final file to contain:
1. If you don't want to keep the original AnalogSignal around after it gets sliced, remove it from the ChannelIndex before writing the first time. The NIX files wont contain the original signals at all. I noticed there's more than one in the ChannelIndexes so you would have to clear all references:
    ```python
    for chx in Blk.channel_indexes:
        chx.analogsignals = []
    ```
2. If you do want to keep it around, you can attach all the old AnalogSignals to a Segment. There's more than one, so simply attaching the one that's being sliced wont fix the issue. Again, you'd have to iterate through all:
    ```python
    seg = neo.core.Segment()
    for chx in Blk.channel_indexes:
        seg.analogsignals.extend(chx.analogsignals)
    Blk.segments.append(seg)
    ```
3. If you want to keep it around but don't want to put it in a Segment and just want to keep it on the ChannelIndex, you can clear the `nix_name` annotation on the AnalogSignals before the second write:
    ```python
    for chx in Blk.channel_indexes:
        for asig in chx.analogsignals:
            del asig.annotations["nix_name"]
    ```

The third option will work around the mapping issue and save everything to the file properly, the way it will work when I actually fix the underlying issue. I'll get working on the actual solution in a bit.

**Comment by grg2rsr** [comment] 2018-05-16 12:44
This works perfectly. Thank you very much for your help!

**Closed** 2018-05-16 13:40 UTC

**Comment by achilleas-k** [comment] 2018-05-16 15:11
I just found another issue that you should be aware of, @grg2rsr. it's more serious and it can lead to data loss. I'm opening a separate issue for it and I'll link it here.
