### ISSUE TITLE
Analog signals from Spike2 files are not read in Python

### ISSUE THREAD

**Issue by RParicio** [NeuralEnsemble/python-neo#564] opened 2018-09-10 12:40 UTC
Hi,

I am trying to load Spike2 files using Python 2.7, and I can read the data from some channels, but not the ones containing analog data.

In Spike2, I can see that the data contained in the attached test file contains the following channels:

[File_spike2_1.zip](https://github.com/NeuralEnsemble/python-neo/files/2366583/File_spike2_1.zip)

![spike2 screenshot](https://user-images.githubusercontent.com/41790076/45297918-2f6ef700-b507-11e8-9ec4-f7c94f6bc877.png)

In Python, this is the code I used to load the file:

`import neo`
`reader = neo.io.Spike2IO(filename='C:/Users/Admin/Desktop/File_spike2_1.smr')`
`bl = reader.read(lazy=False, load_waveforms=True)[0]`

If I then type `bl.segments`, I get "[Segment with 5 events, 15 spiketrains, annotations: {'system_id': 4}
 analogsignals (N=0)]"

If I explore the file a little more by typing `bl.segments[0].events`, I see that the data from 5 event channels is correctly loaded (channels 1, 4, 12, 30, 31 in Spike2). However, the channels containing analog signals are missing (channels 2 and 6). 
(Also, whenever a key has been pressed in the keyboard channel, I am not able to see which key was pressed, only that one key was pressed at a given time),

I have been suggested to run the Spike2 format tests (test_spike2rawio.py and test_spike2io.py), and both were successful. A colleague has also tried to load Spike2 data using Python 3, getting the same results as me.

Any help will be greatly appreciated!

**Comment by samuelgarcia** [comment] 2018-09-12 09:13
I will have a look.

**Comment by samuelgarcia** [comment] 2018-09-12 09:50
When I run this:
```python
import neo
reader = neo.io.Spike2IO(filename='RParicio_spike2/File_spike2_1.smr')
bl = reader.read(lazy=False, load_waveforms=True)[0]

for seg in  bl.segments:
    print(seg)
    print('nb channel Analogsignals, ', len(seg.analogsignals))
    for anasig in seg.analogsignals:
        print('  ', anasig.name, anasig.shape, anasig.sampling_rate, anasig.annotations)
    
    print('nb channel Events', len(seg.events))
    for event in seg.events:
        print('  ', event.name, event.annotations)

    print('nb channel Epochs', len(seg.epochs))
    for epoch in seg.epochs:
        print('  ', epoch.name, epoch.annotations)

    print('nb channel Spikstrains', len(seg.spiketrains))
    for sptr in seg.spiketrains:
        print('  ', sptr.name, sptr.shape, sptr.waveforms.shape, sptr.annotations)
```

I have this
```
nb channel Analogsignals,  1
   Channel bundle (Respi)  (45688, 1) 200.80321285140562 Hz {'channel_names': array(['Respi'],
      dtype='<U64'), 'channel_ids': array([1])}
nb channel Events 5
   Stim {'copy': False, 'physical_channel_index': 16, 'comment': 'Created', 'id': '0'}
   V1 {'copy': False, 'physical_channel_index': 16, 'comment': 'Created', 'id': '3'}
   untitled {'copy': False, 'physical_channel_index': 16, 'comment': 'Created', 'id': '11'}
   untitled {'copy': False, 'physical_channel_index': 16, 'comment': 'Created', 'id': '29'}
   Keyboard {'copy': False, 'physical_channel_index': 0, 'comment': '', 'id': '30'}
nb channel Epochs 0
nb channel Spikstrains 15
   untitled (22,) (22, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#0'}
   untitled (39,) (39, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#1'}
   untitled (29,) (29, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#2'}
   untitled (36,) (36, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#3'}
   untitled (33,) (33, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#4'}
   untitled (12,) (12, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#5'}
   untitled (12,) (12, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#6'}
   untitled (9,) (9, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#7'}
   untitled (6,) (6, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#8'}
   untitled (10,) (10, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#9'}
   untitled (6,) (6, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#10'}
   untitled (5,) (5, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#11'}
   untitled (5,) (5, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#12'}
   untitled (7,) (7, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#13'}
   untitled (16,) (16, 1, 102) {'physical_channel_index': -1, 'comment': 'No comment', 'id': 'ch5#14'}
```

What call channel 2 is the respi I think. And the signal is there.

The channel 6 is a problem because this channel apparently have gaps.
And this is not so weel compatible with neo object model. Because channel Respi which is continuous should be assign to one Segment. And Channel 6 with gaps shoudl be assign to several segment.

In fact I discovered another bug Spike2RawIO.
Line 120 ```if chan_info['kind'] in [1, 9]:``` should be replace by ```if chan_info['kind'] in [1, 6]:```.

If you do this change, now neo.Spike2IO have the correct behavior which is raise an error because inconsistency in Segment for AnalogSignal.
```AssertionError: Signal channel have differents pause so diffrents nb_segment```

But if I do the patch, the case will be worst for you : you won't be able to read this file anymore.
I think, I must introduce a new karg ```eliminate_channel_with_gaps=False/True``` that would control this.

In neo, the case one signal channel do not have gaps and one signal channel have gaps is not covered (nor in core nor in rawio nore in io).
The case of all channels have the same gaps is covered with creating several Segment for each chunk.

**Comment by samuelgarcia** [comment] 2018-09-20 08:01
Spyder must not be blamed here nor this OS.

The problem is in our code and the fact the AnalogSignal in neo must not have no gaps. (unless for SpikeTrain with some waveforms).
So in the case or SMR, I think the best to detect if a signals have gaps, then to detect if the length of small chunk are constant and then move this signal channel to a spiketrain channel with waveforms.

I must confess that this patch would not be a not leisur coding time.

In my opinion, recording only small chunks of a continuous signal is a general bad pratctice .
I would advice to record continuously all channels. And then, to code an offline waveform extract above threshold which 5 lines of code.

In propose to fix this right now by detecting gaps and trigg a warning if a signal channel have gaps.
If I will have more time, I will add an option to load signals with gaps into spiketrain with waveforms.
Is it OK ?

**Comment by RParicio** [comment] 2018-09-20 08:21
Thanks for the reply.

In fact, this is a test file, and for me it's no big deal if analog data with gaps can't be loaded, as I will generally record continuously.
Our main problem is that we can't even load continuous analog signals (which you could do).  I see that issue #540 might have the same problem.
Any idea why this could be?

**Comment by samuelgarcia** [comment] 2018-09-20 08:27
Oups.
forget everything I have said before.
There is not bug in the neo spike2rawio code.

Your channel 6 ( one based) is in fact the channel 5 (0 based)
This channel  already **is** a spiketrain channel with waveforms.
But you activated certainly a spike sorter on this so all chunk are spread in diffrents clusters.

Run this to anderstand
```python
import neo
import matplotlib.pyplot as plt

reader = neo.io.Spike2IO(filename='File_spike2_1.smr')
bl = reader.read(lazy=False, load_waveforms=True)[0]

for seg in  bl.segments:
    print('nb channel Spikstrains', len(seg.spiketrains))
    
    fig, axs = plt.subplots(nrows=4, ncols=4)
    for i, sptr in enumerate(seg.spiketrains):
        print('  ', sptr.name, sptr.shape, sptr.waveforms.shape, sptr.annotations)
        ax = axs.flatten()[i]
        ax.plot(sptr.waveforms[:, 0, :].T, color='k')

plt.show()
```

You will get this
```
nb channel Spikstrains 15
   untitled (22,) (22, 1, 102) {'id': 'ch5#0', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (39,) (39, 1, 102) {'id': 'ch5#1', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (29,) (29, 1, 102) {'id': 'ch5#2', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (36,) (36, 1, 102) {'id': 'ch5#3', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (33,) (33, 1, 102) {'id': 'ch5#4', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (12,) (12, 1, 102) {'id': 'ch5#5', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (12,) (12, 1, 102) {'id': 'ch5#6', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (9,) (9, 1, 102) {'id': 'ch5#7', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (6,) (6, 1, 102) {'id': 'ch5#8', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (10,) (10, 1, 102) {'id': 'ch5#9', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (6,) (6, 1, 102) {'id': 'ch5#10', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (5,) (5, 1, 102) {'id': 'ch5#11', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (5,) (5, 1, 102) {'id': 'ch5#12', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (7,) (7, 1, 102) {'id': 'ch5#13', 'physical_channel_index': -1, 'comment': 'No comment'}
   untitled (16,) (16, 1, 102) {'id': 'ch5#14', 'physical_channel_index': -1, 'comment': 'No comment'}

```

**'id': 'ch5#0'** means channel 5 cluster 0
**'id': 'ch5#1'** means channel 5 cluster 1
**...**

**(22, 1, 102)** means 22 "spikes" for 1 channel with 102 samples
**(39, 1, 102)** means 39 "spikes" for 1 channel with 102 samples
**...**

![figure_smr_waveforms](https://user-images.githubusercontent.com/815627/45805351-d8171680-bcbe-11e8-9894-1a760d0243e2.png)

**Comment by samuelgarcia** [comment] 2018-09-20 08:28
OK.
So be sure to use the github master.

```
pip uninstall neo
pip install https://github.com/NeuralEnsemble/python-neo/archive/master.zip
```

**Comment by samuelgarcia** [comment] 2018-09-20 08:31
```python
import neo
import matplotlib.pyplot as plt

reader = neo.io.Spike2IO(filename='File_spike2_1.smr')
bl = reader.read(lazy=False, load_waveforms=True)[0]

for seg in  bl.segments:
    print(seg)
    print('nb channel Analogsignals, ', len(seg.analogsignals))
    fig, ax = plt.subplots()
    for anasig in seg.analogsignals:
        print('  ', anasig.name, anasig.shape, anasig.sampling_rate, anasig.annotations)
        ax.plot(anasig.times, anasig, color='k')

plt.show()
```

```
<neo.core.segment.Segment object at 0x7fc968ea1ef0>
nb channel Analogsignals,  1
   Channel bundle (Respi)  (45688, 1) 200.80321285140562 Hz {'channel_names': array(['Respi'], dtype='<U64'), 'channel_ids': array([1])}
```

![figure_spike2_signal](https://user-images.githubusercontent.com/815627/45806058-59bb7400-bcc0-11e8-8321-4728e069303d.png)

**Comment by RParicio** [comment] 2018-09-20 09:06
It works!! Thanks a lot.

With the version of neo I had installed before, I could run the code you posted and see the spike waveforms, but not the last one with the full analog signal of channel "respi".
I then used the github master to install neo and now your last code works as well. I have tried other .smr files and I can also load the analogsignals.

Thanks a lot!

**Comment by RParicio** [comment] 2018-09-20 09:29
Yes, sure

**Closed** 2018-09-20 09:37 UTC
