### ISSUE TITLE
Slow loading time of Neuralynx data

### ISSUE THREAD

**Issue by yairlak** [NeuralEnsemble/python-neo#1193] opened 2022-11-03 12:29 UTC
I'm using python-neo to read Neuralynx data, however, loading time is very slow compared to, e.g., using MATLAB's NPMK.

The way I'm currently reading it is as follows:
reader = neo.io.NeuralynxIO(dirname=path2data)
time0, timeend = reader.global_t_start, reader.global_t_stop
sfreq = reader.get_signal_sampling_rate()
channels = reader.header['signal_channels']
ch_names = [channel[0] for channel in channels]
        
n_segments_list = reader.header['nb_segment'] # list of n_segments
chunks = []
for i_block, n_segments in enumerate(n_segments_list):
    for i_segment in range(n_segments):
        print(f'block {i_block+1}; Segment {i_segment+1}/{n_segments}')
        curr_chunk = reader.get_analogsignal_chunk(block_index=i_block,
                                                   seg_index=i_segment)
        chunks.append(curr_chunk)
data = np.vstack(chunks)

Then, I'm generating an MNE-python Raw object:
info = mne.create_info(ch_names=ch_names,
                       sfreq=sfreq, ch_types='seeg')
raw = mne.io.RawArray(data.T, info, verbose=False)

My data folder contains ncs files of ~200MB per channel, with a total of ~20GB of data (~100 channels). 
Data loading can take more than a day, rather than a couple of hours at most. Often, python also crashes due to memory overload, although I use nodes with more than 64GB of RAM. 

What is the best way to use neo for simply reading neuralynx data into a 2d numpy array (n_channels X n_timepoints)?

**Environment:**
 - Linux Ubuntu
 - Python version > 3.6
 - Neo version 0.11

Thanks

**Comment by JuliaSprenger** [comment] 2022-11-03 13:12
```python
reader = neo.io.NeuralynxIO(dirname=path2data)
time0, timeend = reader.global_t_start, reader.global_t_stop
sfreq = reader.get_signal_sampling_rate()
channels = reader.header['signal_channels']
ch_names = [channel[0] for channel in channels]

n_segments_list = reader.header['nb_segment'] # list of n_segments
chunks = []
for i_block, n_segments in enumerate(n_segments_list):
    for i_segment in range(n_segments):
        print(f'block {i_block+1}; Segment {i_segment+1}/{n_segments}')
        curr_chunk = reader.get_analogsignal_chunk(block_index=i_block, seg_index=i_segment)
        chunks.append(curr_chunk)
data = np.vstack(chunks)

# Then, I'm generating an MNE-python Raw object:
info = mne.create_info(ch_names=ch_names, sfreq=sfreq, ch_types='seeg')
raw = mne.io.RawArray(data.T, info, verbose=False)
```

Hi @yairlak,
you can probably save a bit of overhead by using the `NeuralynxRawIO` + `reader.parse_header()`  instead of the `NeuralynxIO`, since you are anyway not using the top-level IO features.
Note that depending on the data files you have the IO might already require to read all files on initialisation / header parsing. This might take some time, but to the extend you are reporting. The reading of the data chunks via `get_analogsignal_chunk` should also be relatively fast and memory efficient, as this should just return a memory map. Could you check  which part of your code takes the majority of the time? Is spend in the initialisation of the IO or the handling of the data chunks?

Note that via concatenating all segments across all blocks you are loosing time information and should not run analysis comparing channels across time.

**Comment by yairlak** [comment] 2022-11-03 13:27
Thank you Julie,
Could you only clarify your last comment regarding loosing time information
when concatenating all blocks together?
In my case, often there's only a single block when reading, so
concatenation is done only across segments in most cases - will there be
time information lost also in this case?

In general,
I didn't find a clear example in the documentation - what would be the
simplest, fastest and most memory efficient way to just retrieve *all*
recorded channel data into a numpy array, such that no time information is
lost.

I would like to use python-neo in my projects but I'm worried that I'm not
finding the right way for this simple goal.

Many thanks in advance,
Yair.

**Comment by JuliaSprenger** [comment] 2022-11-03 13:42
Hi @yairlak,
Regarding the timing across segments: The NeuralynxIO only generates multiple segments in case the recorded data is not continuous. So if you find more than one segment this means there's was either an intentional pause in the recording or the system did loose some samples during the recording. In both cases you need an explicit starting time of the 2nd segment and can just assume all data was continuously sampled. By concatenating signals across segments you are ignoring this and treat all data as continuously sampled. If this is what you are aiming for then concatenating the segments the way you implement it is the way to go. For investigating which part of the code takes the majority of time / resources I would propose to run tests on a subset of your ncs files.

**Comment by JuliaSprenger** [comment] 2022-11-03 14:29
Most likely this is caused by the recording system not being able to save all data in time, and therefore loosing some data packets from time to time, which is a common issue with Neuralynx data. However I haven't encountered a dataset with that many missing data points, usually you might find <10 segments.
Probably the amount of data lost each time is minimal, but still by just stacking all your data you might accumulate a relevant difference between the real time a sample was recorded and the sampling time you implicitly assume in the stacked version of your data. For a start you could compare these times to decide if the time difference has a magnitude relevant to you.

**Comment by JuliaSprenger** [comment] 2023-04-03 13:09
Closing this for now. Feel free to reopen if there's news on your side.

**Closed by JuliaSprenger** 2023-04-03 13:09 UTC
Labels: question
