### ISSUE TITLE
Pickle fails in python 3.6

### ISSUE THREAD

**Issue by Christian-B** [NeuralEnsemble/python-neo#529] opened 2018-05-02 19:22 UTC
test script:
```python
#code taken from http://neo.readthedocs.io/en/0.6/api_reference.html#neo.core.Block
from neo.core import (Block, Segment, ChannelIndex, AnalogSignal)
from quantities import nA, kHz
import numpy as np

#create a Block with 3 Segment and 2 ChannelIndex objects
blk = Block()
for ind in range(3):
    seg = Segment(name='segment %d' % ind, index=ind)
blk.segments.append(seg)

for ind in range(2):
    chx = ChannelIndex(name='Array probe %d' % ind, index=np.arange(64))
    blk.channel_indexes.append(chx)
# Populate the Block with AnalogSignal objects
for seg in blk.segments:
    for chx in blk.channel_indexes:
        a = AnalogSignal(np.random.randn(10000, 64)*nA,
                         sampling_rate=10*kHz)
        chx.analogsignals.append(a)
        seg.analogsignals.append(a)
# code to write pickle
from neo.io import PickleIO
import pickle

io = PickleIO(filename="temp.pkl")

io.write(blk)

#code to read pickle back
with open("temp.pkl") as pkl:
    neo = pickle.load(pkl)
```

===
result
```
Traceback (most recent call last):
File ".../test.py", line 34, in 
neo = pickle.load(pkl)
File "/usr/lib/python3.6/codecs.py", line 321, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
```

**Comment by apdavison** [comment] 2018-10-22 16:44
As a workaround, replace the last two lines with:
```python
io = PickleIO(filename="temp.pkl")
blk2 = io.read()[0]
```

This is the intended way to read files created with PickleIO, but I guess reading them directly with the `pickle` module should also work, so I'll leave the ticket open.

**Comment by samuelgarcia** [comment] 2021-07-26 14:55
I propose to close this now.

**Closed by samuelgarcia** 2021-07-26 14:55 UTC
Labels: IO, bug

**Comment by Christian-B** [comment] 2021-07-26 15:39
Please explain the reason for closing this!

How was it fixed or is a choice to never fix this bug!

**Comment by samuelgarcia** [comment] 2021-07-26 16:09
This issue was pretty old.
Before evry release we clean some very quiete issue tyherads.
In my mind the solution of `io = PickleIO(filename="temp.pkl")` is the way to go.
Please re-open this issue if necessary.

**Comment by apdavison** [comment] 2021-07-26 16:13
on revisiting this, I think the problem is that in the example code the file was opened in text  mode, not binary.

It should be:
```
#code to read pickle back
with open("temp.pkl", "rb") as pkl:
    neo = pickle.load(pkl)
```

**Comment by Christian-B** [comment] 2021-07-27 07:38
The closed will not fix would have been a reasonable approach forcing the creator (in this case me) to argue why the issue was important even if old.

The answer from @apdavison was even better and I can confirm 100% correct.   

Thanks!
